# Generated by Django 5.2.13 on 2026-04-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Menu name (e.g. Main Navigation, Footer Links)",
                        max_length=80,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier used to retrieve this menu in templates",
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("header", "Header Navigation"),
                            ("footer", "Footer Navigation"),
                            ("sidebar", "Sidebar Navigation"),
                            ("admin_primary", "Admin Primary Navigation"),
                            ("admin_account", "Admin Account Navigation"),
                        ],
                        default="header",
                        help_text="Where this menu appears on the site",
                        max_length=30,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active menus are rendered"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order when multiple menus share a location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Text displayed for this menu item", max_length=80
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("url", "URL (absolute or relative)"),
                            ("named_url", "Django Named URL"),
                            ("anchor", "Page Anchor (#section)"),
                        ],
                        default="url",
                        help_text="How to interpret the URL value",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL, Django URL name, or anchor. Examples: '/about/', 'home:all', '#contact'",
                        max_length=300,
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, help_text="Open link in a new browser tab"
                    ),
                ),
                (
                    "css_class",
                    models.CharField(
                        blank=True,
                        help_text="Optional CSS classes for custom styling",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier (e.g. SVG name or icon class)",
                        max_length=60,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hidden items are not rendered"
                    ),
                ),
                (
                    "requires_auth",
                    models.BooleanField(
                        default=False, help_text="Only show to authenticated users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="landing.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="landing.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "label"],
                "abstract": False,
            },
        ),
    ]
