# Generated by Django 5.2.13 on 2026-04-19 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name (e.g. About, Services)",
                        max_length=80,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Name must be at least 2 characters"
                            )
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True, default="")),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short heading displayed at the top of the section",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introductory description for the section",
                        max_length=400,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "abstract": False,
            },
        ),
    ]
