# Generated by Django 5.2.13 on 2026-04-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="background_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to background image (relative to static/)",
                max_length=420,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich body content for content/profile sections",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="content_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the content model this section displays (e.g. 'studio', 'product', 'person'). Leave blank for sections with only inline content.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Call-to-action button label",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="cta_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Call-to-action link target (URL or #anchor)",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short label displayed above the heading",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("content", "Content"),
                    ("profile", "Profile"),
                    ("card_grid", "Card Grid"),
                    ("contact_form", "Contact Form"),
                    ("custom", "Custom"),
                ],
                default="content",
                help_text="Controls how the section renders (hero, card grid, etc.)",
                max_length=20,
            ),
        ),
    ]
